### ISSUE TITLE
execute[Setting sysctl: net.core.somaxconn] 

### ISSUE THREAD

**Issue by gldalmaso** [aws/opsworks-cookbooks#123]
I'm trying to create an Ubuntu 12.04 instance (no custom ami), chef 11.10 and I'm receiving the following error:

```
[2014-04-02T12:26:08+00:00] INFO: Processing directory[/etc/sysctl.d] action create (opsworks_initial_setup::sysctl line 1)
[2014-04-02T12:26:08+00:00] INFO: Processing template[/etc/sysctl.d/70-opsworks-defaults.conf] action create (opsworks_initial_setup::sysctl line 8)
[2014-04-02T12:26:08+00:00] INFO: template[/etc/sysctl.d/70-opsworks-defaults.conf] created file /etc/sysctl.d/70-opsworks-defaults.conf
[2014-04-02T12:26:08+00:00] INFO: template[/etc/sysctl.d/70-opsworks-defaults.conf] updated file contents /etc/sysctl.d/70-opsworks-defaults.conf
[2014-04-02T12:26:08+00:00] INFO: template[/etc/sysctl.d/70-opsworks-defaults.conf] owner changed to 0
[2014-04-02T12:26:08+00:00] INFO: template[/etc/sysctl.d/70-opsworks-defaults.conf] group changed to 0
[2014-04-02T12:26:08+00:00] INFO: template[/etc/sysctl.d/70-opsworks-defaults.conf] mode changed to 644
[2014-04-02T12:26:08+00:00] INFO: Processing execute[Setting sysctl: net.core.somaxconn] action run (opsworks_initial_setup::sysctl line 17)

================================================================================
Error executing action `run` on resource 'execute[Setting sysctl: net.core.somaxconn]'
================================================================================


Errno::ENOENT
-------------
No such file or directory - sysctl


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache/cookbooks/opsworks_initial_setup/recipes/sysctl.rb

17:   execute "Setting sysctl: #{systcl}" do
18:     command "sysctl -w #{systcl}=#{value}"
19:     action :run
20:   end
21: end



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache/cookbooks/opsworks_initial_setup/recipes/sysctl.rb:17:in `block in from_file'

execute("Setting sysctl: net.core.somaxconn") do
action [:run]
retries 0
retry_delay 2
command "sysctl -w net.core.somaxconn=1024"
backup 5
returns 0
cookbook_name "opsworks_initial_setup"
recipe_name "sysctl"
end



[2014-04-02T12:26:08+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-04-02T12:26:08+00:00] ERROR: Running exception handlers
[2014-04-02T12:26:08+00:00] ERROR: Exception handlers complete
[2014-04-02T12:26:08+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-04-02T12:26:08+00:00] ERROR: execute[Setting sysctl: net.core.somaxconn] (opsworks_initial_setup::sysctl line 17) had an error: Errno::ENOENT: No such file or directory - sysctl
[2014-04-02T12:26:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by ujuettner** [comment]
I guess, you're using Chef 11.10 and chef_gem somewhere in your cookbooks. If so, we are currently about to ship a fix for that issue.

**Comment by grampajoe** [comment]
Is there any way to work around the issue with chef_gem until it's fixed?

**Comment by gldalmaso** [comment]
Yeah, there was probably a chef_gem in one of the community cookbooks dependencies. I ended up using a simpler one that fit my need. Thanks for the insight.

**Comment by ujuettner** [comment]
The AWS OpsWorks Instance Agent version 306, which includes the fix, is now rolled out. The release-chef-11.10 branch is updated accordingly.

**Comment by webgress** [comment]
getting same exact error :

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2014-08-26T02:27:29+00:00] INFO: Processing execute[Setting sysctl: net.core.somaxconn] action run (opsworks_initial_setup::sysctl line 17)

# 

# Error executing action `run` on resource 'execute[Setting sysctl: net.core.somaxconn]'

## Errno::ENOENT

No such file or directory - sysctl

## Resource Declaration:

# In /var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_initial_setup/recipes/sysctl.rb

17:   execute "Setting sysctl: #{systcl}" do
18:     command "sysctl -w #{systcl}=#{value}"
19:     action :run
20:   end
21: end

## Compiled Resource:

# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_initial_setup/recipes/sysctl.rb:17:in `block in from_file'

execute("Setting sysctl: net.core.somaxconn") do
action [:run]
retries 0
retry_delay 2
command "sysctl -w net.core.somaxconn=1024"
backup 5
returns 0
cookbook_name "opsworks_initial_setup"
recipe_name "sysctl"
end
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

and here is the version : 

opsworks-agent-cli agent_report

AWS OpsWorks Instance Agent State Report:

  Last activity was a "setup" on 2014-08-26 02:28:44 UTC
  Agent Status: The AWS OpsWorks agent is running as PID 1118
  Agent Version: 323, up to date

HELP !!!!!

**Comment by awsrequena** [comment]
What is your configuration? EC2 instance type, OS, arch

thx
