### ISSUE TITLE
Deploy failing on downloading ruby rpm file

### ISSUE THREAD

**Issue by dignoe** [aws/opsworks-cookbooks#170]
My deploys are failing while trying to download the ruby rpm file. I'm getting 403 Forbidden errors.

```
...
[2014-07-19T14:48:45-06:00] INFO: Processing remote_file[/tmp/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm] action create_if_missing (ruby::default line 44)
[2014-07-19T14:48:45-06:00] DEBUG: remote_file[/tmp/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm] checking for changes
[2014-07-19T14:48:45-06:00] DEBUG: Sending HTTP Request via GET to opsworks-instance-assets.s3.amazonaws.com:443/packages/amazon/2013.09/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm
[2014-07-19T14:48:45-06:00] DEBUG: Streaming download from https://opsworks-instance-assets.s3.amazonaws.com/packages/amazon/2013.09/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm to tempfile /tmp/chef-rest20140719-20381-15o7bzq-0

================================================================================
Error executing action `create_if_missing` on resource 'remote_file[/tmp/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm]'
================================================================================


Net::HTTPServerException
------------------------
403 "Forbidden"


Resource Declaration:
---------------------
# In /opt/aws/opsworks/releases/20140624205147_229/cookbooks/ruby/recipes/default.rb

44:   remote_file "/tmp/#{node[:ruby][:rpm]}" do
45:     source node[:ruby][:rpm_url]
46:     action :create_if_missing
47: 
48:     not_if do
49:       local_ruby_up_to_date
50:     end
51:   end
52: 



Compiled Resource:
------------------
# Declared in /opt/aws/opsworks/releases/20140624205147_229/cookbooks/ruby/recipes/default.rb:44:in `from_file'

remote_file("/tmp/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm") do
retry_delay 2
cookbook_name :ruby
backup 5
retries 0
path "/tmp/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm"
recipe_name "default"
action [:create_if_missing]
provider Chef::Provider::RemoteFile
not_if { #code block }
end



[2014-07-19T14:48:45-06:00] INFO: Running queued delayed notifications before re-raising exception
[2014-07-19T14:48:45-06:00] DEBUG: Re-raising exception: Net::HTTPServerException - remote_file[/tmp/opsworks-ruby19-1.9.3-p547-1.x86_64.rpm] (ruby::default line 44) had an error: Net::HTTPServerException: 403 "Forbidden"
/usr/lib/ruby/1.8/net/http.rb:2105:in `error!'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/rest.rb:259:in `streaming_request'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/rest.rb:280:in `retriable_rest_request'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/rest.rb:236:in `streaming_request'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/remote_file.rb:46:in `action_create'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/file.rb:252:in `action_create_if_missing'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `send'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `run_action'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in `run_action'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:50:in `run_action'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `each'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:81:in `converge'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:404:in `converge'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:469:in `do_run'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in `run'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in `run_application'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `run_application'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
/opt/aws/opsworks/releases/20140624205147_229/vendor/gems/chef-11.4.4/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16
```

**Comment by jweiss** [comment]
See my comment here: https://github.com/aws/opsworks-cookbooks/commit/9b8c63fd7e501cdbb741727bda4c7b8fdd2cd96e#commitcomment-7071303

**Comment by dignoe** [comment]
The [documentation](http://docs.aws.amazon.com/opsworks/latest/userguide/workinginstances-os.html) says to run `update_dependencies` in order to manually update the Amazon Linux release. When I do this, I get the exact same error.

I added the following to my custom JSON, which let me update the dependencies.

``` json
{
  "opsworks": {
    "ruby_stack": "ruby",
    "ruby_version": "1.9.3-p545"
  }
}
```
