### ISSUE TITLE
rails recipe: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by till** [aws/opsworks-cookbooks#182]
Brand new stack on Chef 11.10 — we're not using rails, but I guess it's used anyway?

```
[2014-08-07T18:42:25+00:00] INFO: Starting chef-zero on port 8889 with repository at repository at /opt/aws/opsworks/current
One version per cookbook
data_bags at /var/lib/aws/opsworks/data/data_bags
nodes at /var/lib/aws/opsworks/data/nodes

[2014-08-07T18:42:25+00:00] INFO: Forking chef instance to converge...
[2014-08-07T18:42:25+00:00] INFO: *** Chef 11.10.4 ***
[2014-08-07T18:42:25+00:00] INFO: Chef-client pid: 1155
[2014-08-07T18:42:26+00:00] INFO: Setting the run_list to ["opsworks_custom_cookbooks::load", "opsworks_custom_cookbooks::execute"] from JSON
[2014-08-07T18:42:26+00:00] WARN: Run List override has been provided.
[2014-08-07T18:42:26+00:00] WARN: Original Run List: [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2014-08-07T18:42:26+00:00] WARN: Overridden Run List: [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2014-08-07T18:42:26+00:00] INFO: Run List is [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2014-08-07T18:42:26+00:00] INFO: Run List expands to [opsworks_custom_cookbooks::load, opsworks_custom_cookbooks::execute]
[2014-08-07T18:42:26+00:00] INFO: Starting Chef Run for hhvm1.localdomain
[2014-08-07T18:42:26+00:00] INFO: Running start handlers
[2014-08-07T18:42:26+00:00] INFO: Start handlers complete.
[2014-08-07T18:42:26+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: /reports/nodes/hhvm1.localdomain/runs
[2014-08-07T18:42:36+00:00] INFO: Loading cookbooks [apache2, dependencies, deploy, gem_support, mod_php5_apache2, mysql, nginx, opsworks_agent_monit, opsworks_berkshelf, opsworks_bundler, opsworks_commons, opsworks_custom_cookbooks, opsworks_initial_setup, opsworks_java, opsworks_nodejs, opsworks_rubygems, packages, passenger_apache2, php, rails, ruby, scm_helper, ssh_users, unicorn]

================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache/cookbooks/rails/attributes/rails.rb
================================================================================


TypeError
---------
no implicit conversion of Symbol into Integer


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache/cookbooks/deploy/attributes/deploy.rb:52:in `[]'
/var/lib/aws/opsworks/cache/cookbooks/deploy/attributes/deploy.rb:52:in `block in from_file'
/var/lib/aws/opsworks/cache/cookbooks/deploy/attributes/deploy.rb:50:in `each'
/var/lib/aws/opsworks/cache/cookbooks/deploy/attributes/deploy.rb:50:in `from_file'
/var/lib/aws/opsworks/cache/cookbooks/deploy/attributes/default.rb:17:in `from_file'
/var/lib/aws/opsworks/cache/cookbooks/rails/attributes/rails.rb:17:in `from_file'


Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache/cookbooks/deploy/attributes/deploy.rb:

45:  end
46:  
47:  default[:opsworks][:rails][:ignore_bundler_groups] = ['test', 'development']
48:  
49:  default[:deploy] = {}
50:  node[:deploy].each do |application, deploy|
51:    default[:deploy][application][:deploy_to] = "/srv/www/#{application}"
52>>   default[:deploy][application][:chef_provider] = node[:deploy][application][:chef_provider] ? node[:deploy][application][:chef_provider] : node[:opsworks][:deploy_chef_provider]
53:    unless valid_deploy_chef_providers.include?(node[:deploy][application][:chef_provider])
54:      raise "Invalid chef_provider '#{node[:deploy][application][:chef_provider]}' for app '#{application}'. Valid providers: #{valid_deploy_chef_providers.join(', ')}."
55:    end
56:    default[:deploy][application][:keep_releases] = node[:deploy][application][:keep_releases] ? node[:deploy][application][:keep_releases] : node[:opsworks][:deploy_keep_releases]
57:    default[:deploy][application][:current_path] = "#{node[:deploy][application][:deploy_to]}/current"
58:    default[:deploy][application][:document_root] = ''
59:    default[:deploy][application][:ignore_bundler_groups] = node[:opsworks][:rails][:ignore_bundler_groups]
60:    if deploy[:document_root]
61:      default[:deploy][application][:absolute_document_root] = "#{default[:deploy][application][:current_path]}/#{deploy[:document_root]}/"



[2014-08-07T18:42:37+00:00] ERROR: Running exception handlers
[2014-08-07T18:42:37+00:00] ERROR: Exception handlers complete
[2014-08-07T18:42:37+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache/chef-stacktrace.out
[2014-08-07T18:42:37+00:00] ERROR: no implicit conversion of Symbol into Integer
[2014-08-07T18:42:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by till** [comment]
Ah, I guess the following is the problem:

As soon as you use `node["deploy"]` for attributes (e.g. `node["deploy"]["foo"]["bar"]`) (via the stack's JSON), the recipe assumes that `node["deploy"]["foo"]` is an application and then gets stuck because it can't find all the values OpsWorks populates/adds for an application.

Could be a _nicer_ error, or more robust code? 

Would file this as a feature request though!

**Comment by awsrequena** [comment]
yes, we expect `node["deploy"]["foo"]` to be the definition for an app, this is the way the JSON send to the instance is defined.

What feature request do you have in mind?

**Comment by till** [comment]
@awsrequena defensive programming, build a wrapper around `node["deploy"]` which checks if the JSON structure is _complete_ in a way that it doesn't break when people use it.

Additionally, a note in the docs that `node["deploy"]` is not to be touched.
