### ISSUE TITLE
Failed setup when stopping and re-starting a system with a RAID array

### ISSUE THREAD

**Issue by heffergm** [aws/opsworks-cookbooks#188]
After successfully provisioning a host with an EBS RAID10, I get the following error if I then shut down and restart the host. The volume is already mounted successfully when this tries to run. Commenting out the offending block allows the host to complete setup.

```
[2014-08-14T10:58:16+00:00] INFO: Processing execute[mkfs_/dev/lvm-raid-0/lvm0] action nothing (ebs::raids line 18)
[2014-08-14T10:58:16+00:00] INFO: Processing ruby_block[Create or attach LVM volume out of /dev/md0] action nothing (ebs::raids line 23)
[2014-08-14T10:58:16+00:00] INFO: Processing ruby_block[Create or resume RAID array /dev/md0] action run (ebs::raids line 32)
[2014-08-14T10:58:16+00:00] INFO: Checking for existing RAID arrays at /dev/md0: true
[2014-08-14T10:58:16+00:00] INFO: Checking for running RAID arrays at /dev/md0: false
[2014-08-14T10:58:16+00:00] INFO: Resuming existing RAID array /dev/md0 with 8 disks, RAID level 10 at /var/lib/postgresql
[2014-08-14T10:58:16+00:00] INFO: mdadm: looking for devices for /dev/md0
mdadm: /dev/xvdj is busy - skipping
mdadm: /dev/xvdk is busy - skipping
mdadm: /dev/xvdl is busy - skipping
mdadm: /dev/xvdm is busy - skipping
mdadm: /dev/xvdn is busy - skipping
mdadm: /dev/xvdo is busy - skipping
mdadm: /dev/xvdp is busy - skipping
mdadm: /dev/xvdq is busy - skipping


[2014-08-14T10:58:16+00:00] INFO: Stopping /dev/md127
[2014-08-14T10:58:16+00:00] INFO: mdadm: Cannot get exclusive access to /dev/md127:Perhaps a running process, mounted filesystem or active volume group?


[2014-08-14T10:58:16+00:00] INFO: mdadm: looking for devices for /dev/md0
mdadm: /dev/xvdj is busy - skipping
mdadm: /dev/xvdk is busy - skipping
mdadm: /dev/xvdl is busy - skipping
mdadm: /dev/xvdm is busy - skipping
mdadm: /dev/xvdn is busy - skipping
mdadm: /dev/xvdo is busy - skipping
mdadm: /dev/xvdp is busy - skipping
mdadm: /dev/xvdq is busy - skipping



================================================================================
Error executing action `run` on resource 'ruby_block[Create or resume RAID array /dev/md0]'
================================================================================


RuntimeError
------------
Failed to assemble the RAID array at /dev/md0


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/libraries/block_device.rb:128:in `assemble_raid'
/var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb:38:in `block (3 levels) in from_file'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb

 32:   ruby_block "Create or resume RAID array #{raid_device}" do
 33:     block do
 34:       if BlockDevice.existing_raid_at?(raid_device)
 35:         if BlockDevice.assembled_raid_at?(raid_device)
 36:           Chef::Log.info "Skipping RAID array at #{raid_device} - already assembled and probably mounted at #{options[:mount_point]}"
 37:         else
 38:           BlockDevice.assemble_raid(raid_device, options)
 39:         end
 40:       else
 41:         BlockDevice.create_raid(raid_device, options.update(:chunk_size => node[:ebs][:mdadm_chunk_size]))
 42:       end
 43:       BlockDevice.set_read_ahead(raid_device, node[:ebs][:md_read_ahead])



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb:32:in `block in from_file'

ruby_block("Create or resume RAID array /dev/md0") do
  action "run"
  retries 0
  retry_delay 2
  block_name "Create or resume RAID array /dev/md0"
  cookbook_name "ebs"
  recipe_name "raids"
  block #<Proc:0x007fabeff10ed0@/var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb:33>
end



[2014-08-14T10:58:17+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-08-14T10:58:17+00:00] ERROR: Running exception handlers
[2014-08-14T10:58:17+00:00] ERROR: Exception handlers complete
[2014-08-14T10:58:17+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2014-08-14T10:58:17+00:00] ERROR: ruby_block[Create or resume RAID array /dev/md0] (ebs::raids line 32) had an error: RuntimeError: Failed to assemble the RAID array at /dev/md0
[2014-08-14T10:58:17+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
^C
root@postgis3:/var/lib/aws/opsworks/chef# vgdisplay
  --- Volume group ---
  VG Name               lvm-raid-0
  System ID
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  2
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                1
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               2.00 TiB
  PE Size               4.00 MiB
  Total PE              524159
  Alloc PE / Size       524159 / 2.00 TiB
  Free  PE / Size       0 / 0
  VG UUID               9KkQL3-lXpW-lgGf-on3o-3Dyl-m1mf-FwHclN
```

**Comment by awsrequena** [comment]
I'll try to reproduce the problem.

Can you please provide the exact configuration you're attempting to use? (i.e. OS, instance type, RAID configuration, etc)

**Comment by awsrequena** [comment]
I cannot reproduce your issue on:
- Default Stack
  - EBS instances
  - Chef 11.10
  - no custom cookbooks
  - no custom JSON
- Custom Layer
  - RAID10
    - 4 disk
    - standard volumes
- Instance
  - Amazon Linux 64 bit
  - EC2 instance type c3.large

**Comment by heffergm** [comment]
My system configuration:
- r3.4xl
- ubuntu 11.10
- RAID10
  - 8 disk
  - gp ssd volumes

To clarify what I mentioned earlier about 'start and restart the host', specifically:
- issue a 'stop' via opsworks
- issue a 'start' via opsworks
- host reports the error during the running_setup phase of coming online

If I comment out the following block of code from /opt/aws/opsworks/current/cookbooks/ebs/recipes/raids.rb and re-run setup, the process completes without error:

```
 32   #ruby_block "Create or resume RAID array #{raid_device}" do
 33   #  block do
 34   #    if BlockDevice.existing_raid_at?(raid_device)
 35   #      if BlockDevice.assembled_raid_at?(raid_device)
 36   #        Chef::Log.info "Skipping RAID array at #{raid_device} - already assembled and probably mounted at #{options[:mount_point]}"
 37   #      else
 38   #        BlockDevice.assemble_raid(raid_device, options)
 39   #      end
 40   #    else
 41   #      BlockDevice.create_raid(raid_device, options.update(:chunk_size => node[:ebs][:mdadm_chunk_size]))
 42   #    end
 43   #    BlockDevice.set_read_ahead(raid_device, node[:ebs][:md_read_ahead])
 44   #  end
 45   #  notifies :create, "ruby_block[Create or attach LVM volume out of #{raid_device}]", :immediately
 46   #end
```

**Comment by nickjwebb** [comment]
I also get this issue on every ops works instance we run. I can't believe it's not a widespread issue, but perhaps it's not.

We create an 8 drive RAID0 volume, and on initial setup it comes up as md0 when created, but after stop/start or reboot it comes up as md127 and then when the setup runs it hangs:

```
[2015-01-09T21:43:53+00:00] INFO: mdadm: looking for devices for /dev/md0
mdadm: /dev/xvdi is busy - skipping
mdadm: /dev/xvdj is busy - skipping
mdadm: /dev/xvdk is busy - skipping
mdadm: /dev/xvdl is busy - skipping
mdadm: /dev/xvdm is busy - skipping
mdadm: /dev/xvdn is busy - skipping
mdadm: /dev/xvdo is busy - skipping
mdadm: /dev/xvdp is busy - skipping


[2015-01-09T21:43:53+00:00] INFO: Deactivating volume group lvm-raid-0
[2015-01-09T21:43:53+00:00] INFO:   Logical volume lvm-raid-0/lvm0 contains a filesystem in use.
Can't deactivate volume group "lvm-raid-0" with 1 open logical volume(s)


[2015-01-09T21:43:53+00:00] INFO: Stopping /dev/md127
[2015-01-09T21:43:54+00:00] INFO: mdadm: Cannot get exclusive access to /dev/md127:Perhaps a running process, mounted filesystem or active volume group?


[2015-01-09T21:43:54+00:00] INFO: mdadm: looking for devices for /dev/md0
mdadm: /dev/xvdi is busy - skipping
mdadm: /dev/xvdj is busy - skipping
mdadm: /dev/xvdk is busy - skipping
mdadm: /dev/xvdl is busy - skipping
mdadm: /dev/xvdm is busy - skipping
mdadm: /dev/xvdn is busy - skipping
mdadm: /dev/xvdo is busy - skipping
mdadm: /dev/xvdp is busy - skipping



================================================================================
Error executing action `run` on resource 'ruby_block[Create or resume RAID array /dev/md0]'
================================================================================


RuntimeError
------------
Failed to assemble the RAID array at /dev/md0


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/libraries/block_device.rb:128:in `assemble_raid'
/var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb:38:in `block (3 levels) in from_file'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb

32:   ruby_block "Create or resume RAID array #{raid_device}" do
33:     block do
34:       if BlockDevice.existing_raid_at?(raid_device)
35:         if BlockDevice.assembled_raid_at?(raid_device)
36:           Chef::Log.info "Skipping RAID array at #{raid_device} - already assembled and probably mounted at #{options[:mount_point]}"
37:         else
38:           BlockDevice.assemble_raid(raid_device, options)
39:         end
40:       else
41:         BlockDevice.create_raid(raid_device, options.update(:chunk_size => node[:ebs][:mdadm_chunk_size]))
42:       end
43:       BlockDevice.set_read_ahead(raid_device, node[:ebs][:md_read_ahead])



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb:32:in `block in from_file'

ruby_block("Create or resume RAID array /dev/md0") do
action "run"
retries 0
retry_delay 2
block_name "Create or resume RAID array /dev/md0"
cookbook_name "ebs"
recipe_name "raids"
block #<Proc:0x007fd124102b90@/var/lib/aws/opsworks/cache.stage2/cookbooks/ebs/recipes/raids.rb:33>
end



[2015-01-09T21:43:54+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-09T21:43:54+00:00] ERROR: Running exception handlers
[2015-01-09T21:43:54+00:00] ERROR: Exception handlers complete
[2015-01-09T21:43:54+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2015-01-09T21:43:54+00:00] ERROR: ruby_block[Create or resume RAID array /dev/md0] (ebs::raids line 32) had an error: RuntimeError: Failed to assemble the RAID array at /dev/md0
[2015-01-09T21:43:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Super frustrating. I can't see any solution, other than opsworks not specifying the device number. Our setup works fine as we are mounting the resultant lv (/dev/lvm-raid-0/lvm0), but since setup fails and changes won't run and the instance is tagged as "setup_failed".

Let me know if I can help resolve this issue... I've seen it on all 4 of our instances that have OpsWorks and RAID, all running the latest ALAMI (2014.09) with OpsWorks.

**Comment by tomobk** [comment]
I think this issue is "raid array mapping problem ".
I tried following command,and It worked well.
#sudo update-initramfs -u

More information  site
http://ubuntuforums.org/showthread.php?t=1764861&page=2

**Comment by djcp** [comment]
This is still a problem with _ubuntu 14.04 hosts_. I fixed it by writing a custom recipe to run during setup that just executes "update-initramfs -u". To replicate:
- create a stack with ubuntu 14.04 as the OS
- create a layer with RAID'd ebs mounts
- Add an instance to that layer. Start it.
- Stop the instance.
- Start it again. It should fail when attempting to recreate the RAID array.

**Comment by nwsheppard** [comment]
This is still a problem.  Do you plan on fixing this?

**Comment by djcp** [comment]
I fixed it with a chef recipe run during the setup lifecycle event: https://github.com/harvard-dce/mh-opsworks-recipes/blob/master/recipes/fix-raid-mapping.rb

It's an issue with ubuntu, not opsworks.

**Comment by nwsheppard** [comment]
Well I am seeing it in Amazon Linux 2015.03 too. Oh and thanks for pointing me to that location.  I saw it above and just didn't pursue it.

**Comment by djcp** [comment]
oh, weird. I thought this was just with ubuntu.

**Comment by nwsheppard** [comment]
It looks be be an issue with mdadm not being able to handle the problems it encounters.  Thank you for the recipe.  In RHEL variants > 6.x you just have to run 'dracut -f' to rebuild the initramfs of the running kernel.

**Comment by jsh2134** [comment]
I am having the same issue with Ubuntu/Opsworks/EBS - thanks for the fix @djcp 

One thing to note for others debugging: for instances that already had failed setup, I had to run `sudo update-initramfs -u` command manually and then start/stop the instance again for it to pass setup.

**Comment by n1t1nv3rma** [comment]
For AMZN Linux workaround: https://forums.aws.amazon.com/thread.jspa?threadID=159429

**Comment by gorandev** [comment]
@heffergm Why was this closed? It keeps happening, I'm dealing with it right now.

**Comment by chaseconey** [comment]
Also experiencing this issue - is there a more permanent fix on the horizon?

**Comment by agolan-amazon** [comment]
@gorandev and @chaseconey, we'd be happy to take a look, would you be able to provide your account details?
If so, Please send them to my email address

**Comment by toddlers** [comment]
still facing the issue .

**Comment by nickjwebb** [comment]
@toddlers since the latest version of OpsWorks (Chef 12) doesn't support RAID anymore, I'd assume this is never going to be improved. Given the gp2 (SSD) storage now support volumes up to 16TB in size, it's also not needed as much (although, yes, you can probably get better performance out of a RAID of EBS volumes versus a single one, but usually a single volume is good enough).
