### ISSUE TITLE
New apache2 MiniSpec Test Fails

### ISSUE THREAD

**Issue by gfawcettpq** [aws/opsworks-cookbooks#215]
The latest release of the apache2 cookbook to allow the apache group to be overridden has introduced a broken test that causes our deployments to fail if we have enabled the run_cookbook_tests option (which we do to run our own integration tests).

```
[2014-09-16T11:42:51+00:00] ERROR: MiniTest failed with 0 failure(s) and 2 error(s).
Error:
recipe::apache2::default::services#test_0002_runs as the expected user:
Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ps -e -o ppid,user | grep 17899
 | uniq ----
STDOUT: 17899 apache
17899 apache
17899 apache
STDERR: sh: -c: line 1: syntax error near unexpected token `|'
sh: -c: line 1: ` | uniq'
---- End output of ps -e -o ppid,user | grep 17899
 | uniq ----
Ran ps -e -o ppid,user | grep 17899
 | uniq returned 1
    /opt/aws/opsworks/releases/20140909102228_325/vendor/bundle/ruby/2.0.0/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout.rb:257:in `invalid!'
    /opt/aws/opsworks/releases/20140909102228_325/vendor/bundle/ruby/2.0.0/gems/mixlib-shellout-1.4.0/lib/mixlib/shellout.rb:244:in `error!'
    /var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_commons/libraries/shellout.rb:8:in `shellout'
    /opt/aws/opsworks/current/merged-cookbooks/apache2/specs/default_spec.rb:70:in `block (3 levels) in <top (required)>'
```

The issue is that the apache_pid returned to insert into the shellout command includes a newline character which is causing | uniq to be executed as a separate command by the shell.  The pid value should be chomped before being returned.

```
 def apache_pid
    @apache_pid = "#{::File.read node[:apache][:pid_file]}".chomp
  end
```

**Comment by ujuettner** [comment]
Thanks. We've already came across this, too. A fix will be included in the next version.
