### ISSUE TITLE
"Deploy an App" failed due to removing cookbooks/ssh_users/libraries/user.rb

### ISSUE THREAD

**Issue by tsuda7** [aws/opsworks-cookbooks#222]
I have trouble deploying my app.

I executed "Deploy an App" for my layer which includes some recipes in "Deploy" in "Custom Chef Recipes" setting and got the following error.
(I examined some patterns and found that a layer which doesn't include any recipes in "Deploy" can occur this error.)

```
[2014-09-30T11:35:22+09:00] INFO: Forking chef instance to converge...
[2014-09-30T11:35:22+09:00] INFO: *** Chef 11.10.4 ***
[2014-09-30T11:35:22+09:00] INFO: Chef-client pid: 16288
[2014-09-30T11:35:23+09:00] INFO: Setting the run_list to ["opsworks_custom_cookbooks::load", "opsworks_custom_cookbooks::execute"] from JSON
[2014-09-30T11:35:23+09:00] WARN: Run List override has been provided.
[2014-09-30T11:35:23+09:00] WARN: Original Run List: [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2014-09-30T11:35:23+09:00] WARN: Overridden Run List: [recipe[deploy::default], recipe[opsworks_stack_state_sync], recipe[test_suite], recipe[opsworks_cleanup]]
[2014-09-30T11:35:23+09:00] INFO: Run List is [recipe[deploy::default], recipe[opsworks_stack_state_sync], recipe[test_suite], recipe[opsworks_cleanup]]
[2014-09-30T11:35:23+09:00] INFO: Run List expands to [deploy::default, opsworks_stack_state_sync, test_suite, opsworks_cleanup]
[2014-09-30T11:35:23+09:00] INFO: Starting Chef Run for api-agg2.localdomain
[2014-09-30T11:35:23+09:00] INFO: Running start handlers
[2014-09-30T11:35:23+09:00] INFO: Start handlers complete.
[2014-09-30T11:35:23+09:00] INFO: HTTP Request Returned 404 Not Found: Object not found: /reports/nodes/api-agg2.localdomain/runs
[2014-09-30T11:35:29+09:00] INFO: Loading cookbooks [dependencies, deploy, gem_support, opsworks_bundler, opsworks_cleanup, opsworks_commons, opsworks_initial_setup, opsworks_nodejs, opsworks_rubygems, opsworks_stack_state_sync, packages, ruby, test_suite]
[2014-09-30T11:35:29+09:00] INFO: Removing cookbooks/ssh_users/recipes/default.rb from the cache; its cookbook is no longer needed on this client.
[2014-09-30T11:35:29+09:00] INFO: Removing cookbooks/ssh_users/templates/default/sudoers.erb from the cache; its cookbook is no longer needed on this client.
[2014-09-30T11:35:29+09:00] INFO: Removing cookbooks/ssh_users/libraries/user.rb from the cache; its cookbook is no longer needed on this client.
[2014-09-30T11:35:29+09:00] INFO: Removing cookbooks/ssh_users/attributes/default.rb from the cache; its cookbook is no longer needed on this client.
[2014-09-30T11:35:29+09:00] INFO: Removing cookbooks/ssh_users/attributes/customize.rb from the cache; its cookbook is no longer needed on this client.
[2014-09-30T11:35:29+09:00] INFO: Removing cookbooks/ssh_users/metadata.rb from the cache; its cookbook is no longer needed on this client.

...
(omission)
...

================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/recipes/default.rb
================================================================================


NoMethodError
-------------
undefined method `next_free_uid' for Chef::Resource::User


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_user.rb:9:in `block (2 levels) in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_user.rb:6:in `block in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/recipes/default.rb:5:in `block in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/recipes/default.rb:3:in `each'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/recipes/default.rb:3:in `from_file'


Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_user.rb:

2:    deploy = params[:deploy_data]
3:  
4:    group deploy[:group]
5:  
6:    user deploy[:user] do
7:      action :create
8:      comment "deploy user"
9>>     uid next_free_uid
10:      gid deploy[:group]
11:      home deploy[:home]
12:      supports :manage_home => true
13:      shell deploy[:shell]
14:      not_if do
15:        existing_usernames = []
16:        Etc.passwd {|user| existing_usernames << user['name']}
17:        existing_usernames.include?(deploy[:user])
18:      end



[2014-09-30T11:35:29+09:00] ERROR: Running exception handlers
[2014-09-30T11:35:29+09:00] ERROR: Exception handlers complete
[2014-09-30T11:35:29+09:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2014-09-30T11:35:29+09:00] ERROR: undefined method `next_free_uid' for Chef::Resource::User
[2014-09-30T11:35:29+09:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

This error occurred because the function `next_free_uid` was not defined. I found its defined in cookbooks/ssh_users/libraries/user.rb which was removed in a previous step. (See the steps before "omission")

I solved this problem by adding OpsWorks's "ssh_users" recipe into "Deploy" in "Custom Chef Recipes", but this solution seems weird.

If this is a bug, I would appreciate its fix.
Thanks in advance.

**Comment by zerowolfgang** [comment]
I'm surprised that this has not even been acknowledged yet, but I have also had to deal with the same missing `next_free_uid` definition as well as missing definitions for `scm_helper` and `passenger_apache2` (before I found this issue) that prevented "Deploy and App" executing successfully.
 If this is to/can be expected in order to get things done, it could be helpful to have at least a passing mention in the docs, or as per @tsuda7, confirmed if this is a bug.

Danke.

**Comment by mihai-chiorean** [comment]
having the same error when I try to customize deploy just to override some attributes
