### ISSUE TITLE
Setup of AWS Flow (Ruby) layer fails

### ISSUE THREAD

**Issue by baruchlubinsky** [aws/opsworks-cookbooks#223]
I'm using Ubuntu 14.04 and I get this error: 

```
Error executing action `run` on resource 'ruby_block[restart AWS Flow Ruby application workers]'

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /srv/www/workers/current/runner.initrc restart ----
STDOUT: workers failed to start
STDERR: cat: /var/log/workers.{log,err}: No such file or directory
---- End output of /srv/www/workers/current/runner.initrc restart ----
Ran /srv/www/workers/current/runner.initrc restart returned 1


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_commons/libraries/    shellout.rb:8:in `shellout'
/var/lib/aws/opsworks/cache.stage2/cookbooks/opsworks_aws_flow_ruby/definitions/opsworks_aws_flow_ruby.rb:63:in `block (3 levels) in from_file'
```

**Comment by redterror** [comment]
Any reason not to merge this?  It fixes the issue for me on ubuntu 14.04.
