### ISSUE TITLE
[rails] Recipe Compile Error / undefined method `gsub' for 460828230686509:Fixnum

### ISSUE THREAD

**Issue by ellmo** [aws/opsworks-cookbooks#237]
This thing just happened to me while trying to deploy a rails app. It wouldn't go away (even tho I deployed the app succefully many times on the previous days.)

Desperate and thinking I've done something wrong I stopped my instance and try to setup/configure it from the ground up. It's showing again and basically failing cookbooks before any real work starts.

Please help

```
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/libraries/escape_characters.rb:5:in `block in escape'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/libraries/escape_characters.rb:5:in `each'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/libraries/escape_characters.rb:5:in `map'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/libraries/escape_characters.rb:5:in `escape'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/libraries/escape_characters.rb:9:in `escape_double_quotes'
/var/lib/aws/opsworks/cache.stage2/cookbooks/unicorn/recipes/rails.rb:49:in `block (2 levels) in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/unicorn/recipes/rails.rb:41:in `block in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/unicorn/recipes/rails.rb:9:in `each'
/var/lib/aws/opsworks/cache.stage2/cookbooks/unicorn/recipes/rails.rb:9:in `from_file'
```

```
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/libraries/escape_characters.rb:

1:  module OpsWorks
2:    module Escape
3:  
4:      def self.escape(env, pattern, sub)
5>>       Hash[env.map{|key, value| [key, value.nil? ? value : value.gsub(pattern, sub)]}]
6:      end
7:  
8:      def self.escape_double_quotes(env)
9:        escape(env, /\"/, "\\\"")
10:      end
11:  
12:      def self.escape_xml(env)
13:        escape(env, /[&"'<>]/, {"&" => "&amp;", "\"" => "&quot;", "'" => "&apos;", "<" => "&lt;", ">" => "&gt;"})
14:      end
```

**Comment by ellmo** [comment]
Hm, this was actually a problem in my custom chef JSON, where one of the variables was not stringified (tho it was a perfectly valid integer).

**Comment by firecentaur** [comment]
thanks, in my case, my stack settings in opsworks had a nested object which was causing the issue, un nested and then it worked
