### ISSUE TITLE
chef-11.10 incompatible with kitchen-ec2

### ISSUE THREAD

**Issue by bbergstrom** [aws/opsworks-cookbooks#263]
The release-chef-11.10 branch of cookbooks do not work on EC2 instances created outside of OpsWorks.  It appears OpsWorks is doing some amount of setup before using Chef.  This preperation should happen in the built in cookbooks or have graceful defaults when used on a regular EC2 instance to allow for use with test kitchen.  This is not a problem with the release-chef-11.4 branch.

This is the error I am hitting:

```
  * opsworks_commons_assets_installer[Install user space OpsWorks ruby package] action install       [2014-12-18T19:05:09+00:00] INFO: Processing opsworks_commons_assets_installer[Install user space OpsWorks ruby package] action install (ruby::default line 39)

================================================================================       
Error executing action `install` on resource 'opsworks_commons_assets_installer[Install user space OpsWorks ruby package]'       
================================================================================       


       Errno::ENOENT
       -------------
       No such file or directory - /var/lib/aws/opsworks/client.yml



       Cookbook Trace:
---------------       
       /tmp/kitchen/cache/cookbooks/opsworks_commons/libraries/opsworks_instance_agent_config_parser.rb:13:in `opsworks_chef_config'
       /tmp/kitchen/cache/cookbooks/opsworks_commons/libraries/opsworks_instance_agent_config_parser.rb:39:in `default_cookbooks_path'
       /tmp/kitchen/cache/cookbooks/opsworks_commons/providers/assets_installer.rb:66:in `local_asset'
       /tmp/kitchen/cache/cookbooks/opsworks_commons/providers/assets_installer.rb:5:in `block in class_from_file'



Resource Declaration:       
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/ruby/recipes/default.rb

        39:   opsworks_commons_assets_installer "Install user space OpsWorks ruby package" do
        40:     asset package_name
        41:     version node[:ruby][:version]
        42:     release node[:ruby][:pkgrelease]
        43: 
        44:     notifies :write, "log[downloading]", :immediately
        45:     action :install
        46:   end
        47: end




       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/ruby/recipes/default.rb:39:in `from_file'

       opsworks_commons_assets_installer("Install user space OpsWorks ruby package") do
         action [:install]
         retries 0
         retry_delay 2
         cookbook_name "ruby"
         recipe_name "default"
         asset "opsworks-ruby19"
         version "1.9.3-p551"
         release "1"
       end



       [2014-12-18T19:05:09+00:00] INFO: Running queued delayed notifications before re-raising exception

       Running handlers:
       [2014-12-18T19:05:09+00:00] ERROR: Running exception handlers
       Running handlers complete

       [2014-12-18T19:05:09+00:00] ERROR: Exception handlers complete
       [2014-12-18T19:05:09+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 29 resources updated in 49.676421875 seconds
       [2014-12-18T19:05:09+00:00] ERROR: opsworks_commons_assets_installer[Install user space OpsWorks ruby package] (ruby::default line 39) had an error: Errno::ENOENT: No such file or directory - /var/lib/aws/opsworks/client.yml
       [2014-12-18T19:05:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

A full log of my re-creation can be found here: https://travis-ci.org/sportngin-cookbooks/opsworks-kitchen-compatibility/builds/44492433

**Comment by willkelleher** [comment]
@bbergstrom any luck resolving this?

**Comment by BlueHotDog** [comment]
same issue

**Comment by bbergstrom** [comment]
Nope, just crickets.

https://forums.aws.amazon.com/thread.jspa?messageID=592991&#592991

**Comment by anfleene** [comment]
This is still a huge pain for us :disappointed:

**Comment by elitechance** [comment]
One work around is to copy the missing file: /var/lib/aws/opsworks/client.yml from your ec2 instance to your guest box.

**Comment by chuangtim** [comment]
@elitechance are u resolved this problem,I also meet it, share your way .

**Comment by elitechance** [comment]
@chuangtim - I encounter this when I was trying to simulate opsworks-cookbooks to my local environment.  You can fix this issue by copying the missing file **/var/lib/aws/opsworks/client.yml** to the external instance.  You can check my recipe in [github](https://github.com/elitechance/opsworks-cookbooks-wrapper/blob/master/recipes/default.rb#L54-L58).
