### ISSUE TITLE
Custom recipe fails during instance setup but works from "execute_recipes" in Stack

### ISSUE THREAD

**Issue by alexgorbatchev** [aws/opsworks-cookbooks#28]
Trying to install mongodb from https://github.com/alexgorbatchev/d-opsworks

Here's my layer config

![screen shot 2013-05-02 at 4 16 37 pm](https://f.cloud.github.com/assets/65633/456933/7218a5f0-b37e-11e2-850b-f0820ed4adc3.png)

Here's the error I get

```
...
[Thu, 02 May 2013 23:00:20 +0000] INFO: service[monit]: restarted successfully
[Thu, 02 May 2013 23:00:20 +0000] DEBUG: Processing ruby_block[restart node.js application tinytypo_test] on nodejs-app1.localdomain
[Thu, 02 May 2013 23:00:20 +0000] INFO: restart node.js via: monit restart node_web_app_tinytypo_test
[Thu, 02 May 2013 23:00:21 +0000] INFO: 
[Thu, 02 May 2013 23:00:21 +0000] INFO: apt_repository[10gen] sending run action to execute[apt-get update]immediately (delayed)
[Thu, 02 May 2013 23:00:21 +0000] ERROR: Running exception handlers
[Thu, 02 May 2013 23:00:21 +0000] ERROR: Exception handlers complete
[Thu, 02 May 2013 23:00:27 +0000] DEBUG: Re-raising exception: NoMethodError - undefined method `run_action' for #<Hash:0x7fd312efcbe8>
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/runner.rb:53:in `run_action'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/runner.rb:101:in `converge'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/runner.rb:97:in `each'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/runner.rb:97:in `converge'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/client.rb:268:in `converge'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/client.rb:158:in `run'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/application/solo.rb:190:in `run_application'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/application/solo.rb:181:in `loop'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/application/solo.rb:181:in `run_application'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/../lib/chef/application.rb:62:in `run'
/opt/aws/opsworks/releases/20130429142335_115/vendor/bundle/ruby/1.8/gems/chef-0.9.15.5/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16
```

And here's the same two recipes executed in from the stack's run command.

![screen shot 2013-05-02 at 4 16 01 pm](https://f.cloud.github.com/assets/65633/456934/9343b7ce-b37e-11e2-89cf-442d3dcb0651.png)

I would love it to be consistent... not working so that I can fix it, or working so that I don't have to :)

Any idea? What am i doing wrong?

**Comment by alexgorbatchev** [comment]
I got it to work in both by using

```
notifies :run, resources(:execute => "apt-get update"), :immediately
```

instead of

```
notifies :run, { resources("execute[apt-get update]") => [:immediately] }
```

So, it's not "an issue" for me any more, but it's still very strange that it worked from "run_commands"
