### ISSUE TITLE
Recipe Compile Error on OpsWorks Attribute in OpsWorks Cookbook

### ISSUE THREAD

**Issue by jcderose** [aws/opsworks-cookbooks#317]
I'm writing a cookbook that references OpsWorks attributes and requires including multiple OpsWorks cookbooks. In particular, Chef is giving me an error when looking for the `node[:opsworks][:instance][:infrastructure_class]` attribute.

Here's my Berksfile:

```
source "https://supermarket.chef.io"

metadata
cookbook 'deploy', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'deploy'
cookbook 'dependencies', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'dependencies'
cookbook 'gem_support', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'gem_support'
cookbook 'opsworks_nodejs', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'opsworks_nodejs'
cookbook 'scm_helper', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'scm_helper'
cookbook 'mod_php5_apache2', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'mod_php5_apache2'
cookbook 'ssh_users', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'ssh_users'
cookbook 'opsworks_agent_monit', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'opsworks_agent_monit'
cookbook 'opsworks_java', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'opsworks_java'
cookbook 'opsworks_aws_flow_ruby', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'opsworks_aws_flow_ruby'
cookbook 'opsworks_commons', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'opsworks_commons'
cookbook 'opsworks_initial_setup', git: "https://github.com/aws/opsworks-cookbooks.git", branch: "release-chef-11.10", rel: 'opsworks_initial_setup'
```

And here's my output (with the error):

``` ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/opsworks_initial_setup/attributes/default.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `[]' for nil:NilClass

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/opsworks_commons/libraries/predicates.rb:2:in `infrastructure_class?'
         /tmp/kitchen/cache/cookbooks/opsworks_initial_setup/attributes/default.rb:65:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/opsworks_commons/libraries/predicates.rb:

         1:  def infrastructure_class?(other)
         2>>   node[:opsworks][:instance][:infrastructure_class] == other
         3:  end
         4:


       Running handlers:
       [2015-06-18T22:48:38+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-06-18T22:48:38+00:00] ERROR: Exception handlers complete
       [2015-06-18T22:48:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 123.919626761 seconds
       [2015-06-18T22:48:38+00:00] ERROR: undefined method `[]' for nil:NilClass
       [2015-06-18T22:48:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jcderose** [comment]
For the record, I was able to manually define the `node[:opsworks][:instance][:infrastructure` attribute in my custom JSON block (and compile the cookbook dependency successfully) but I still could not find the attribute definition in the opsworks-cookbooks repo.

**Comment by jarv** [comment]
@jcderose To answer you question about the attribute definition this is either set to "ec2" or "on-premises" as there is some special logic that is done for ec2. It may make sense to default this attribute for now I would just set it as an attribute in your kitchen.yml file.
