### ISSUE TITLE
S3 Archive Application Source fails since 3432

### ISSUE THREAD

**Issue by rjsen** [aws/opsworks-cookbooks#372]
I'm trying to upgrade to 3433 since it's apparently required to launch new instances but can't because of an error fetching S3 sources. We're using Chef 11.10, Berkshelf 3.2.0, and running on Ubuntu 14.04. The stacktrace is below; please let me know if you need any additional info.

```
Generated at 2016-03-07 21:01:33 +0000
NoMethodError: undefined method `s3_url' for Chef::Resource::S3File
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/resource.rb:294:in `method_missing'
/var/lib/aws/opsworks/cache.stage2/cookbooks/scm_helper/libraries/s3.rb:50:in `block in prepare_s3_checkouts'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:123:in `instance_eval'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:123:in `build_resource'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:86:in `declare_resource'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:42:in `method_missing'
/var/lib/aws/opsworks/cache.stage2/cookbooks/scm_helper/libraries/s3.rb:42:in `prepare_s3_checkouts'
/var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy.rb:38:in `block in from_file'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:75:in `instance_eval'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:75:in `evaluate_resource_definition'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:39:in `method_missing'
/var/lib/aws/opsworks/cache.stage2/cookbooks/admiral/recipes/deploy.rb:13:in `block in from_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/admiral/recipes/deploy.rb:4:in `each'
/var/lib/aws/opsworks/cache.stage2/cookbooks/admiral/recipes/deploy.rb:4:in `from_file'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/cookbook_version.rb:237:in `load_recipe'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context.rb:151:in `load_recipe'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/run_context.rb:86:in `load'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/policy_builder/expand_node_object.rb:75:in `setup_run_context'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:252:in `setup_run_context'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:413:in `do_run'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:200:in `block in run'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:194:in `fork'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/client.rb:194:in `run'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application.rb:215:in `run_chef_client'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application/client.rb:314:in `block in run_application'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application/client.rb:306:in `loop'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application/client.rb:306:in `run_application'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/lib/chef/application.rb:66:in `run'
/opt/aws/opsworks/releases/20160227053027_3433-20160227053027/vendor/bundle/ruby/2.0.0/gems/chef-11.10.4/bin/chef-client:26:in `<top (required)>'
/opt/aws/opsworks/current/bin/chef-client:16:in `load'
/opt/aws/opsworks/current/bin/chef-client:16:in `<main>'
```

**Comment by workeitel** [comment]
You probably use a very old version of s3_file (https://github.com/adamsb6/s3_file ) which is incompatible with our call in https://github.com/aws/opsworks-cookbooks/blob/ae6b7ffab7b25a55cbd84a236d4bccfb1cf85696/scm_helper/libraries/s3.rb#L50

The s3_url attribute was added a while ago: https://github.com/adamsb6/s3_file/commit/37b2fe2628b0e6fdff77ec125fc3e9b77770654d

**Comment by rjsen** [comment]
Ah yes, someone apparently copied it in somewhere a while ago. Thanks!
