### ISSUE TITLE
Chef 11.4 Chef::Exceptions::ValidationFailed

### ISSUE THREAD

**Issue by gmacdougall** [aws/opsworks-cookbooks#49]
I'm getting a failure using Chef 11.4 and a new opsworks stack.

I get the following stack trace:

```
# Logfile created on Thu Jul 25 17:59:37 +0000 2013 by logger.rb/1.2.6
[2013-07-25T17:59:37+00:00] INFO: *** Chef 11.4.4 ***
[2013-07-25T17:59:38+00:00] DEBUG: Building node object for cupcake.localdomain
[2013-07-25T17:59:38+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2013-07-25T17:59:38+00:00] INFO: Setting the run_list to ["opsworks_custom_cookbooks::load", "opsworks_custom_cookbooks::execute"] from JSON
[2013-07-25T17:59:38+00:00] DEBUG: Applying attributes from json file
[2013-07-25T17:59:38+00:00] DEBUG: Platform is amazon version 2013.03
[2013-07-25T17:59:38+00:00] INFO: Run List is [recipe[opsworks_custom_cookbooks::load], recipe[opsworks_custom_cookbooks::execute]]
[2013-07-25T17:59:38+00:00] INFO: Run List expands to [opsworks_custom_cookbooks::load, opsworks_custom_cookbooks::execute]
[2013-07-25T17:59:38+00:00] INFO: Starting Chef Run for cupcake.localdomain
[2013-07-25T17:59:38+00:00] INFO: Running start handlers
[2013-07-25T17:59:38+00:00] INFO: Start handlers complete.
[2013-07-25T17:59:38+00:00] DEBUG: No chefignore file found at /opt/aws/opsworks/releases/20130724172340_202/cookbooks/chefignore no files will be ignored
[2013-07-25T17:59:39+00:00] DEBUG: No chefignore file found at /opt/aws/opsworks/releases/20130724172340_202/site-cookbooks/chefignore no files will be ignored
[2013-07-25T17:59:39+00:00] DEBUG: Re-raising exception: Chef::Exceptions::ValidationFailed - Option type must be equal to one of: string, array, hash, symbol!  You passed "boolean".
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:126:in `_pv_equal_to'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `send'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `validate'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `validate'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `validate'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/metadata.rb:388:in `attribute'
/opt/aws/opsworks/releases/20130724172340_202/site-cookbooks/dependencies/metadata.rb:18:in `from_file'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:153:in `apply_ruby_metadata'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:96:in `metadata'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:93:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:93:in `metadata'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:86:in `cookbook_version'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:74:in `tap'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:74:in `cookbook_version'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:95:in `load_cookbook'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:69:in `load_cookbooks'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:68:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:68:in `load_cookbooks'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:67:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:67:in `load_cookbooks'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:213:in `setup_run_context'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:467:in `do_run'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in `run'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in `run_application'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `run_application'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16
[2013-07-25T17:59:39+00:00] ERROR: Running exception handlers
[2013-07-25T17:59:39+00:00] ERROR: Exception handlers complete
[2013-07-25T17:59:39+00:00] FATAL: Stacktrace dumped to /opt/aws/opsworks/releases/20130724172340_202/chef-stacktrace.out
[2013-07-25T17:59:39+00:00] DEBUG: Chef::Exceptions::ValidationFailed: Option type must be equal to one of: string, array, hash, symbol!  You passed "boolean".
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:126:in `_pv_equal_to'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `send'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:69:in `validate'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:66:in `validate'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/params_validate.rb:56:in `validate'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/metadata.rb:388:in `attribute'
/opt/aws/opsworks/releases/20130724172340_202/site-cookbooks/dependencies/metadata.rb:18:in `from_file'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:153:in `apply_ruby_metadata'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:96:in `metadata'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:93:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:93:in `metadata'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:86:in `cookbook_version'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:74:in `tap'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_version_loader.rb:74:in `cookbook_version'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:95:in `load_cookbook'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:69:in `load_cookbooks'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:68:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:68:in `load_cookbooks'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:67:in `each'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook_loader.rb:67:in `load_cookbooks'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:213:in `setup_run_context'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:467:in `do_run'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in `run'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in `run_application'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `run_application'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
/opt/aws/opsworks/releases/20130724172340_202/vendor/gems/chef-11.4.4/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16
[2013-07-25T17:59:39+00:00] FATAL: Chef::Exceptions::ValidationFailed: Option type must be equal to one of: string, array, hash, symbol!  You passed "boolean".
```

The offending lines in the cookbook seem to be:

https://github.com/aws/opsworks-cookbooks/blob/master/dependencies/metadata.rb#L22
https://github.com/aws/opsworks-cookbooks/blob/master/dependencies/attributes/default.rb#L7

**Comment by awsrequena** [comment]
The custom cookbooks you are using are not Chef 11 compatible.

The Chef 11 compatible branch of the cookbooks will be published asap.

**Comment by mattetti** [comment]
same issue here, @awsrequena any chance you could a branch with the chef 11 recipes?

**Comment by jbraeuer** [comment]
Please check the new "master-chef-11.4" branch which contains the Chef 11 cookbooks.
Closing here.
