### ISSUE TITLE
opsworks_custom_cookbooks fails with S3 zip files

### ISSUE THREAD

**Issue by alexism** [aws/opsworks-cookbooks#7]
I'm using a zip file to provide custom cookbooks.
During instance setup, everything goes fine until 'scm "Download Custom Cookbooks" '
https://github.com/aws/opsworks-cookbooks/blob/master/opsworks_custom_cookbooks/recipes/checkout.rb#L27

At this point, Chef fails because `git submodule init && git submodule update` returns a non-zero status.

See the logs below. It starts right after prepare_s3_checkouts.

```
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: STDERR: 
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: ---- End output of git init; git add .; git commit -m 'Create temporary repository from downloaded contents.' ----
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Ran git init; git add .; git commit -m 'Create temporary repository from downloaded contents.' returned 0
[Tue, 26 Feb 2013 01:38:03 +0000] INFO: Ran execute[create git repository] successfully
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Processing scm[Download Custom Cookbooks] on mynode-00.localdomain
[Tue, 26 Feb 2013 01:38:03 +0000] INFO: Cloning repo /tmp/opsworks20130226-834-1e0sh27/archive.d to /opt/aws/opsworks/current/site-cookbooks
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Executing git clone  /tmp/opsworks20130226-834-1e0sh27/archive.d /opt/aws/opsworks/current/site-cookbooks
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: ---- Begin output of git clone  /tmp/opsworks20130226-834-1e0sh27/archive.d /opt/aws/opsworks/current/site-cookbooks ----
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: STDOUT: Cloning into '/opt/aws/opsworks/current/site-cookbooks'...
done.
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: STDERR: 
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: ---- End output of git clone  /tmp/opsworks20130226-834-1e0sh27/archive.d /opt/aws/opsworks/current/site-cookbooks ----
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Ran git clone  /tmp/opsworks20130226-834-1e0sh27/archive.d /opt/aws/opsworks/current/site-cookbooks returned 0
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Executing git ls-remote /tmp/opsworks20130226-834-1e0sh27/archive.d HEAD
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Executing git ls-remote /tmp/opsworks20130226-834-1e0sh27/archive.d HEAD
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: ---- Begin output of git ls-remote /tmp/opsworks20130226-834-1e0sh27/archive.d HEAD ----
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: STDOUT: 183e5968347b2c5eb192855230937507f55f32b3   HEAD
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: STDERR: 
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: ---- End output of git ls-remote /tmp/opsworks20130226-834-1e0sh27/archive.d HEAD ----
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Ran git ls-remote /tmp/opsworks20130226-834-1e0sh27/archive.d HEAD returned 0
[Tue, 26 Feb 2013 01:38:03 +0000] INFO: Checking out branch: HEAD reference: 183e5968347b2c5eb192855230937507f55f32b3
[Tue, 26 Feb 2013 01:38:03 +0000] DEBUG: Executing git checkout -b deploy 183e5968347b2c5eb192855230937507f55f32b3
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: ---- Begin output of git checkout -b deploy 183e5968347b2c5eb192855230937507f55f32b3 ----
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: STDOUT: 
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: STDERR: Switched to a new branch 'deploy'
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: ---- End output of git checkout -b deploy 183e5968347b2c5eb192855230937507f55f32b3 ----
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: Ran git checkout -b deploy 183e5968347b2c5eb192855230937507f55f32b3 returned 0
[Tue, 26 Feb 2013 01:38:04 +0000] INFO: Enabling git submodules
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: Executing git submodule init && git submodule update
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: ---- Begin output of git submodule init && git submodule update ----
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: STDOUT: 
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: STDERR: No submodule mapping found in .gitmodules for path 'mongodb'
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: ---- End output of git submodule init && git submodule update ----
[Tue, 26 Feb 2013 01:38:04 +0000] DEBUG: Ran git submodule init && git submodule update returned 1
[Tue, 26 Feb 2013 01:38:04 +0000] ERROR: scm[Download Custom Cookbooks] (/opt/aws/opsworks/releases/20130225142901_104/cookbooks/opsworks_custom_cookbooks/recipes/checkout.rb:27:in `from_file') had an error:
git submodule init && git submodule update returned 1, expected 0
---- Begin output of git submodule init && git submodule update ----
STDOUT: STDERR: No submodule mapping found in .gitmodules for path 'mongodb'
---- End output of git submodule init && git submodule update ----

/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/mixin/command.rb:184:in `handle_command_failures'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/mixin/command.rb:131:in `run_command'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/provider/git.rb:128:in `enable_submodules'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/provider/git.rb:44:in `action_checkout'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource.rb:406:in `send'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource.rb:406:in `run_action'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/runner.rb:53:in `run_action'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/runner.rb:89:in `converge'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/runner.rb:89:in `each'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/runner.rb:89:in `converge'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/runner.rb:84:in `converge'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/client.rb:268:in `converge'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/client.rb:158:in `run'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/application/solo.rb:190:in `run_application'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/application/solo.rb:181:in `loop'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/application/solo.rb:181:in `run_application'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/../lib/chef/application.rb:62:in `run'
/opt/aws/opsworks/releases/20130225142901_104/vendor/bundle/ruby/1.8/gems/chef-0.9.15.3/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in `load'
/opt/aws/opsworks/current/bin/chef-solo:16

```

**Comment by alexism** [comment]
a workaround is to set this custom json in the stack settings:

``` json
{
    "opsworks_custom_cookbooks": {
        "enable_submodules": false
    }
}
```

**Comment by pfcfernandez** [comment]
I have the same issue with some custom cookbooks..

**Comment by mgeens** [comment]
I had the same issue with the rabbitmq cookbook. Thanks for the workaround, alexism.

**Comment by mgeens** [comment]
Unfortunately disabling the submodules results in an empty rabbitmq cookbook folder later on for me.

**Comment by mgeens** [comment]
I found a fix for my case: I'm managing and packaging my cookbooks with Berkshelf, and the rabbitmq cookbook came from a git fork. It was the only cookbook in my tarball that had a .git folder. Removing it made Opsworks happy, with no need to tweak the configuration.
